platform :ios, '11.0' # 根据你的项目需求选择平台版本
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'BLVideoPlayer' do
  pod 'ZFPlayer/AVPlayer'  #4.1.4
  pod 'Cupcake'
  # 添加其他依赖库
end
